"""some fixes in schedule table

Revision ID: da2ea32aef50
Revises: dad338254da9
Create Date: 2023-04-06 16:21:02.659606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2ea32aef50'
down_revision = 'dad338254da9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('day', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'day')
    # ### end Alembic commands ###
