"""some fixes in docs table

Revision ID: dad338254da9
Revises: f9fd73950f15
Create Date: 2023-04-06 15:51:05.882269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad338254da9'
down_revision = 'f9fd73950f15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
